### ISSUE TITLE
[CAN'T FIX] Fix broken moon icon on Brave MacOS?

### ISSUE THREAD

**Issue by NayamAmarshe** [NayamAmarshe/MagLit#12]
![Screenshot 2022-04-15 at 2 50 53 PM](https://user-images.githubusercontent.com/25067102/163553002-1bf059ce-f03d-4fbb-b7f2-50b203aa8413.png)

**Comment by NayamAmarshe** [comment]
No idea why it's happening. Works fine on Safari

**Comment by JimiRecard** [comment]
That looks like iOS version of the moon emoji

**Comment by NayamAmarshe** [comment]
> That looks like iOS version of the moon emoji

For some reason, the emoji icon has no right padding on Brave MacOS but other browsers work just fine. I couldn't find a fix, maybe I should raise an issue on Brave's GitHub.
