### ISSUE TITLE
Add support for curl

### ISSUE THREAD

**Issue by Deissson** [NayamAmarshe/MagLit#23]
Add an option for "curling" the website

In example: curl maglit.me "link" password=12345

I would love to see this option

**Comment by NayamAmarshe** [comment]
That's a cool idea. I'll see if it's possible :)

**Comment by NayamAmarshe** [comment]
Really not sure how to do the `"link" password=xxxx` thing.
Currently, it's possible using this:
```
curl -d '{"slug": "whateverYourSlugIs", "password": "EmptyStringIfNoPassword"}' -H "Content-Type: application/json" -X POST https://maglit.me/api/verify
```
