### ISSUE TITLE
FAQ Dark Mode Black Text

### ISSUE THREAD

**Issue by North-West-Wind** [NayamAmarshe/MagLit#24]
While the website is available in dark mode, the FAQ page still displays with black text, making them very hard to read.

**Comment by NayamAmarshe** [comment]
That's not possible. It should show white text. Can you please reload and check again?
![Screenshot_20220525-132842095](https://user-images.githubusercontent.com/25067102/170211841-daa2033e-1811-4211-8f75-f843ba12c959.jpg)

**Comment by North-West-Wind** [comment]
Reloading doesn't help. I'm using it on Firefox. Perhaps caching causes the problem. I will inform you if clearing the cache solves the problem or not.

**Comment by North-West-Wind** [comment]
Nope, that does not fix it. Running with:
Firefox: 91.9.0esr
Build ID: 20220511230316
OS: Gentoo Linux

I also fired it up in Chromium, and the problem doesn't exist, so it seems to be a Firefox-only issue.

**Comment by NayamAmarshe** [comment]
> Nope, that does not fix it. Running with: Firefox: 91.9.0esr Build ID: 20220511230316 OS: Gentoo Linux
> 
> I also fired it up in Chromium, and the problem doesn't exist, so it seems to be a Firefox-only issue.

Thanks, I'll try to fix it.

**Comment by North-West-Wind** [comment]
I updated Firefox and now it's working.

**Comment by NayamAmarshe** [comment]
> I updated Firefox and now it's working.

Good to know :)
