### ISSUE TITLE
Click on link

### ISSUE THREAD

**Issue by toomuchbrain1** [NayamAmarshe/MagLit#31]
Any possibility to see the number of clicks on a shortened url on the one hosted on your site? 

Can you add it pls even if it's by adding /r in front if the shorten url would be good

**Comment by NayamAmarshe** [comment]
Sorry, this is out of scope for this project. MagLit does not keep logs or number of clicks. If you're hosting the link on your website, you can add a click counter for your links but it would not make sense for MagLit to do it :)
