### ISSUE TITLE
Where is `.ENV.LOCAL_EXAMPLE` file?

### ISSUE THREAD

**Issue by dillfrescott** [NayamAmarshe/MagLit#32]
I can't seem to find it in the repo. Its mentioned in the readme.

**Comment by NayamAmarshe** [comment]
That's strange. I swear it was there haha.

Anyway, you can create a .env.local file in your root directory with the following content:

```
# GET FROM FIREBASE
API_KEY=""
AUTH_DOMAIN=""
PROJECT_ID=""
STORAGE_BUCKET=""

# YOUR OWN STUFF
SECRET_KEY=""

# CAN LEAVE EMPTY
AUTH_KEY=""
```

**Comment by dillfrescott** [comment]
Awesome! Thank you so much!
