### ISSUE TITLE
[Suggestion] Add a way to donate in crypto

### ISSUE THREAD

**Issue by fislysandi** [NayamAmarshe/MagLit#33]
cryptos like monero,btc,etherium,usdt and etc.

and i would like to say thank you for this link shortener.

**Comment by NayamAmarshe** [comment]
Hi, thanks for considering a donation, I really appreciate it!

I do have an eth wallet. Here's the ERC-20 address: 0x14858f5334ea1014e68212c2d4b32792d137f256

Thanks!
