### ISSUE TITLE
Is there an Official Docker Image?

### ISSUE THREAD

**Issue by ItsNoted** [NayamAmarshe/MagLit#36]
I saw the dockerfile but no image or docker compose. Will there be one available soon?

Thank you!

**Comment by NayamAmarshe** [comment]
I'll build a docker image and get back to you.

**Comment by ItsNoted** [comment]
> I'll build a docker image and get back to you.

Sounds good thank you! I'll feature it in todays self hosted roundup! I think our readers will love it!

**Comment by onedr0p** [comment]
Please publish to github container registry and not dockerhub (or publish to both). Dockerhub has container pull rate-limits and terrible retention policies.

**Comment by vutsalsinghal** [comment]
@NayamAmarshe could you also help with ARM image for raspberrypi 🙏🏼
