### ISSUE TITLE
Unable to Install PWA on Desktop

### ISSUE THREAD

**Issue by Penknife0915** [NayamAmarshe/MagLit#47]
Currently,

The PWA can be added to Android devices by selecting "Add to Home screen," but it lacks an "Install" button.

On desktop browsers, the PWA feature is absent. The URL bar doesn't show an installation badge (icon), and there's no "install" item in the browser's drop-down menu.

**Comment by NayamAmarshe** [comment]
MagLit is not a PWA. Nor are there any plans to make it one.
