### ISSUE TITLE
noticed this past week or so

### ISSUE THREAD

**Issue by duelmas** [NayamAmarshe/MagLit#51]
when trying to do post on tweetr with a maglink, ...can't anymore.

![image](https://github.com/NayamAmarshe/MagLit/assets/143072270/82bf2a0b-85db-4723-a925-528738e1fa17)

![image](https://github.com/NayamAmarshe/MagLit/assets/143072270/000550c7-7359-418b-a500-bf5aa4c165e4)

**Comment by NayamAmarshe** [comment]
Probably because of all the phishing links people are creating. Great going!

**Comment by duelmas** [comment]
> Probably because of all the phishing links people are creating. Great going!

aww. I wonder if that can be resolved technically? Well, can't prevent the phishers perhaps but idk.. anyhow, thanks, best link shortener out there. i started w bit.ly... but maglit is great.

**Comment by NayamAmarshe** [comment]
> > Probably because of all the phishing links people are creating. Great going!
> 
> aww. I wonder if that can be resolved technically? Well, can't prevent the phishers perhaps but idk.. anyhow, thanks, best link shortener out there. i started w bit.ly... but maglit is great.

I don't think I'd be able to resolve it unfortunately:(

I cannot get Twitter to unblock the links. Maybe in the future I can add alternative domains :)

**Comment by duelmas** [comment]
perhaps it will just resolve itself at some point like some things are known to do.

**Comment by NayamAmarshe** [comment]
Seems like it's working again now! @duelmas

**Comment by duelmas** [comment]
![image](https://github.com/NayamAmarshe/MagLit/assets/143072270/d334d448-c556-4407-86f7-90e6f5e31e2f)
??

**Comment by duelmas** [comment]
> Seems like it's working again now! @duelmas

I can confirm, all systems go! this image would have looked nicer using [upscayl](https://www.upscayl.org/) >
got quite the workflow doing 4K video batch frames on a 1650 GTX... ;)
![Screen Shot 2024-02-18 at 13 05 43](https://github.com/NayamAmarshe/MagLit/assets/143072270/b3aad888-5ee3-4e98-8e47-6c0b3b346ac9)
o!
