### ISSUE TITLE
Allow TLDs with more than 8 chars.

### ISSUE THREAD

**Issue by willywongi** [NayamAmarshe/MagLit#54]
Using a domain name with a Top Level Domain of more than 8 chars (I had issues with ".education", but [a lot more](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#ICANN-era_generic_top-level_domains) are allowed) results in an error. The message is misleading "Please make sure your link starts with 'http://' or 'https://' or 'magnet://'".
I think the issue stems from the [regexp](https://github.com/NayamAmarshe/MagLit/blob/e32e6ed54addadecee45dc53b3629cde14403cb6/pages/index.jsx#L43) used to test the links.

**Comment by NayamAmarshe** [comment]
I'll update the regex :)

**Comment by NayamAmarshe** [comment]
Fixed in the latest commit.
