### ISSUE TITLE
Add button to copy old links without having to write them out

### ISSUE THREAD

**Issue by CampbellReid** [NayamAmarshe/MagLit#60]
Some button here or something like that. I might even download the source and try to implement something but just have to manage my time.
![image](https://github.com/NayamAmarshe/MagLit/assets/18301812/b6b4e6f3-44cd-44eb-b015-3c1d4c455226)

**Comment by tonydero** [comment]
Not trying to be dismissive here or anything, but doesn't right-click and copy link work?

**Comment by CampbellReid** [comment]
For extra context (I should've included it above), I had the website in a sidebar. Considering my lack of effort into my issue and your comment, I looked into the settings more, there was a touch mode setting enabled which forbode right click. Consider this case resolved, for me at least.
