### ISSUE TITLE
Can't use maglit links in mailings

### ISSUE THREAD

**Issue by NG1843** [NayamAmarshe/MagLit#64]
Somewhere in between August 13 and now the domain maglit.me got a negative reputation on the spamhouse project: https://www.spamhaus.org/domain-reputation?domain=maglit.me
maglit.me got put on the domain blocklist (DBL).

Therefore I can't use the links anymore in the newsletters of my organisation.

Via this link: https://check.spamhaus.org/results/?query=maglit.me it seems it can be arranged the get maglit.me off this list.
But don't think I am the right person to do this, since I do not own this domain.
I post this here in the hope it does reach the right person.
Would the be something else I could do?

**Comment by NayamAmarshe** [comment]
Thank you, I have submitted a request :)

**Comment by notwithering** [comment]
maglit.me looks like it is no longer blocked! i believe this issue can be marked as resolved

![image](https://github.com/user-attachments/assets/fc2dfabe-015d-4c2b-8be7-a4f67112029c)
