### ISSUE TITLE
Notion Links Are Detecting as Suspcious

### ISSUE THREAD

**Issue by mishrabiswajit** [NayamAmarshe/MagLit#66]
**Previously this issue was not present !**

![image](https://github.com/user-attachments/assets/b2a4aeac-c614-4765-8d73-8e4f718a266c)

**Comment by NayamAmarshe** [comment]
Could you please send an example link

**Comment by mishrabiswajit** [comment]
> Could you please send an example link

https://mishrabiswajit.notion.site/Maglit-Test-Page-117b62101fcf80f398bad7c7d6afb9d3?pvs=4

**Comment by NayamAmarshe** [comment]
This should be fixed now. Scammers are using maglit to create scam links and this is why it was happening.

I'm not sure about the future of MagLit tbh. I might shut the website down, it's just too much.
